# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9930f778c4d3b81f7937ed3455d3e375f7233425d59a5d2cae9a3c8b4471308cb5ce7a882414d0c017c1b23cfb7329e40ecc9c43b80bbfa8ebd269f7b485ef95

test:
  secret_key_base: 9099934a1c62ac76da6e3b1ed292a88b9cf1fb243008ac44544758c28a0210ed01c6000dcff1ecbc7ee561f1325d3d4683af27d9ec103907fe6fdbcd8aab636c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
